services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: local-rabbitmq-prac
    ports:
      - "56720:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-db:
    image: postgres:15
    container_name: order-db-prac
    ports:
      - "5441:5432"
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orderuser -d orderdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-db:
    image: postgres:15
    container_name: inventory-db-prac
    ports:
      - "5442:5432"
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: inventoryuser
      POSTGRES_PASSWORD: inventorypass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventoryuser -d inventorydb"]
      interval: 10s
      timeout: 5s
      retries: 5
