package contract;

import au.com.dius.pact.provider.PactVerifyProvider;
import au.com.dius.pact.provider.junit5.MessageTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.example.order.out.messaging.OrderCreatedMessage;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;

// Second provider-side verification. Same pattern as OrderCreatedMessagePactProviderTest
// but verifies the bulk order scenario contract generated by inventory-service.
// No real RabbitMQ or running service needed — just builds the real message in-process.
@Provider("order-service")
@PactFolder("../inventory-service/target/pacts")
@ExtendWith(PactVerificationInvocationContextProvider.class)
public class BulkOrderCreatedMessagePactProviderTest {

    @BeforeEach
    void setTarget(PactVerificationContext context) {
        context.setTarget(new MessageTestTarget());
    }

    @TestTemplate
    void verifyContract(PactVerificationContext context) {
        context.verifyInteraction();
    }

    // Both interactions from the pact file must be handled here since
    // both consumer tests write to the same file (same consumer+provider names).

    @State("an order was created")
    public void toAnOrderWasCreatedState() {
    }

    @PactVerifyProvider("an order created event")
    public String verifyOrderCreatedMessage() throws Exception {
        OrderCreatedMessage message = new OrderCreatedMessage(1L, "Camera", 5);
        return new ObjectMapper().writeValueAsString(message);
    }

    @State("a bulk order was created")
    public void toABulkOrderWasCreatedState() {
    }

    @PactVerifyProvider("a bulk order created event")
    public String verifyBulkOrderCreatedMessage() throws Exception {
        OrderCreatedMessage message = new OrderCreatedMessage(999L, "Laptop", 50);
        return new ObjectMapper().writeValueAsString(message);
    }
}
