spring.datasource.url=jdbc:postgresql://localhost:5442/inventorydb?TimeZone=UTC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=inventoryuser
spring.datasource.password=inventorypass

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.listener.simple.default-requeue-rejected=false

server.port=8082

spring.docker.compose.lifecycle-management=start-only

spring.rabbitmq.host=localhost
spring.rabbitmq.port=56720
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.connection-timeout=30000
